name: null_safe_dart_console_app
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  trotter:
  intl: ^0.17.0
  numeral: ^1.2.4
  number_display: ^3.0.0
  chitose: ^1.1.0